package proyectoparadigmas;

import archivos.AbrirArchivos;
import static archivos.GuardarArchivo.guardarComo;
import java.awt.Color;
import static java.awt.Color.blue;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import parser.Parser;

/**
 * @author Carlos Chacon Vargas
 * @author Bryan Sanchez Brenes
 * @author Diego Quiros Brenes
 * @author Alessandro Fazio Perez
 */
public class ViewDebug extends javax.swing.JFrame {

    private RunExpresion RunExp;
    private boolean debug = false;

    public RunExpresion getRunExp() {
        return RunExp;
        
    }

    public void setRunExp(RunExpresion RunExp) {
        this.RunExp = RunExp;
    }

    /**
     * Creates new form View1
     */
    public ViewDebug(Parser parser,RunExpresion rE,String expresion) {

        this.RunExp = rE;
        initComponents();
        
        this.jTextArea_Expression.setText(expresion);
        jTextArea_Reglas.setText(parser.toString());
        
        Highlighter.HighlightPainter cyanPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.cyan);

        try {
            this.jTextArea_Reglas.getHighlighter().addHighlight(0, 5, cyanPainter);
            
        } catch (BadLocationException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_Expression = new javax.swing.JScrollPane();
        jTextArea_Expression = new javax.swing.JTextArea();
        label_Expression = new javax.swing.JLabel();
        jScrollPane_Resultado = new javax.swing.JScrollPane();
        jTextArea_Resultado = new javax.swing.JTextArea();
        Next = new javax.swing.JButton();
        jScrollPane_Resultado1 = new javax.swing.JScrollPane();
        jTextArea_Reglas = new javax.swing.JTextArea();
        jMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 1 Paradigmas de Programación");
        setLocationByPlatform(true);
        setName("frameMain"); // NOI18N

        jTextArea_Expression.setColumns(20);
        jTextArea_Expression.setRows(5);
        jScrollPane_Expression.setViewportView(jTextArea_Expression);

        label_Expression.setText("Expression: ");

        jTextArea_Resultado.setEditable(false);
        jTextArea_Resultado.setColumns(20);
        jTextArea_Resultado.setRows(5);
        jScrollPane_Resultado.setViewportView(jTextArea_Resultado);

        Next.setText("NEXT");
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
        });
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        jTextArea_Reglas.setEditable(false);
        jTextArea_Reglas.setColumns(20);
        jTextArea_Reglas.setRows(5);
        jScrollPane_Resultado1.setViewportView(jTextArea_Reglas);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_Expression))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_Expression))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane_Resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane_Resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_Expression)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane_Expression, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        this.getRunExp().resume();
    }//GEN-LAST:event_NextActionPerformed

    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked
        
    }//GEN-LAST:event_NextMouseClicked


    
    private void isDebugger(){
        if(!debug){
           // return false;
        }
        else{
            debug = true;
        }
    }
    
    public JTextArea jTextArea_Reglas() {
        return jTextArea_Reglas;
    }

    public JTextArea getjTextArea_Resultado() {
        return jTextArea_Resultado;
    }

    private void limpiarCampos() {
        //jTextArea_Reglas.setText("");
       // jTextArea_Expression.setText("");
        //jTextArea_Resultado.setText("");
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane_Expression;
    private javax.swing.JScrollPane jScrollPane_Resultado;
    private javax.swing.JScrollPane jScrollPane_Resultado1;
    private javax.swing.JTextArea jTextArea_Expression;
    private javax.swing.JTextArea jTextArea_Reglas;
    private javax.swing.JTextArea jTextArea_Resultado;
    private javax.swing.JLabel label_Expression;
    // End of variables declaration//GEN-END:variables

    private boolean ejemplo = false;
}
